#!/usr/bin/env node
/**
 * DS Agent — Icon Generator (ELECTRON_RUN_AS_NODE mode)
 *
 * Generates PNG/ICO/ICNS icons by rendering the SVG in an offscreen BrowserWindow.
 * Run with: npx electron scripts/icon-gen.js
 */

const { app, BrowserWindow, nativeImage } = require('electron');
const fs = require('fs');
const path = require('path');

const ASSETS_DIR = path.join(__dirname, '..', 'assets');
const SVG_PATH = path.join(ASSETS_DIR, 'icon.svg');

app.whenReady().then(async () => {
  if (!fs.existsSync(SVG_PATH)) {
    console.error('❌ icon.svg not found');
    app.quit();
    return;
  }

  const svgContent = fs.readFileSync(SVG_PATH, 'utf-8');

  // Create an offscreen window to render SVG
  const win = new BrowserWindow({
    width: 512,
    height: 512,
    show: false,
    webPreferences: { offscreen: true },
  });

  // Load SVG as data URL
  const svgDataUrl = `data:image/svg+xml;base64,${Buffer.from(svgContent).toString('base64')}`;

  await win.loadURL(svgDataUrl);

  // Wait for render
  await new Promise(r => setTimeout(r, 500));

  // Capture the rendered image
  const image = await win.webContents.capturePage();

  // Resize to 512x512
  const resized = image.resize({ width: 512, height: 512 });

  // Save PNG
  const pngPath = path.join(ASSETS_DIR, 'icon.png');
  fs.writeFileSync(pngPath, resized.toPNG());
  console.log(`✅ ${pngPath}`);

  // Generate ICO (for Windows)
  const png256 = resized.resize({ width: 256, height: 256 });
  const icoBuffer = createIcoFromPng(png256.toPNG());
  const icoPath = path.join(ASSETS_DIR, 'icon.ico');
  fs.writeFileSync(icoPath, icoBuffer);
  console.log(`✅ ${icoPath}`);

  // Generate ICNS (macOS only)
  if (process.platform === 'darwin') {
    const iconsetDir = path.join(ASSETS_DIR, 'icon.iconset');
    if (!fs.existsSync(iconsetDir)) fs.mkdirSync(iconsetDir, { recursive: true });

    const sizes = [
      { name: 'icon_16x16.png', size: 16 },
      { name: 'icon_16x16@2x.png', size: 32 },
      { name: 'icon_32x32.png', size: 32 },
      { name: 'icon_32x32@2x.png', size: 64 },
      { name: 'icon_128x128.png', size: 128 },
      { name: 'icon_128x128@2x.png', size: 256 },
      { name: 'icon_256x256.png', size: 256 },
      { name: 'icon_256x256@2x.png', size: 512 },
      { name: 'icon_512x512.png', size: 512 },
      { name: 'icon_512x512@2x.png', size: 1024 },
    ];

    for (const { name, size } of sizes) {
      const s = resized.resize({ width: size, height: size });
      fs.writeFileSync(path.join(iconsetDir, name), s.toPNG());
    }

    const { execSync } = require('child_process');
    try {
      const icnsPath = path.join(ASSETS_DIR, 'icon.icns');
      execSync(`iconutil -c icns "${iconsetDir}" -o "${icnsPath}"`);
      console.log(`✅ ${icnsPath}`);
    } catch (err) {
      console.log('⚠️  iconutil failed — electron-builder will generate icns from png');
    }
  } else {
    console.log('ℹ️  icon.icns will be auto-generated by electron-builder from icon.png');
  }

  console.log('\n🎉 All icons generated!');
  win.close();
  app.quit();
});

/**
 * Create a basic ICO file from PNG data.
 */
function createIcoFromPng(pngBuffer) {
  const header = Buffer.alloc(6);
  header.writeUInt16LE(0, 0);       // Reserved
  header.writeUInt16LE(1, 2);       // Type: 1 = ICO
  header.writeUInt16LE(1, 4);       // Number of images

  const entry = Buffer.alloc(16);
  entry.writeUInt8(0, 0);           // Width (0 = 256)
  entry.writeUInt8(0, 1);           // Height (0 = 256)
  entry.writeUInt8(0, 2);           // Color palette
  entry.writeUInt8(0, 3);           // Reserved
  entry.writeUInt16LE(1, 4);        // Color planes
  entry.writeUInt16LE(32, 6);       // Bits per pixel
  entry.writeUInt32LE(pngBuffer.length, 8);
  entry.writeUInt32LE(22, 12);      // Offset = 6 + 16

  return Buffer.concat([header, entry, pngBuffer]);
}
